### ISSUE TITLE
Implement a CPU execution thread pool

### ISSUE THREAD

**Issue by benvanik** [google/iree#49]
This can be used for scheduling the SIMD JIT or codegen.

High-level design is of an `iree/task/` task management system that is specialized for our workload (out-of-order dynamic DAGs with late-binding to parameters like dispatch counts). A custom HAL command buffer will produce the DAG fragments consisting of tasks and then submit them to task queues that fan out to a thread pool. cpuinfo will be used by default to create a thread pool that attempts to map one thread to each l2 cache, though this could be overridden.

Major components:
- [x] Synchronization primitives to allow inter-thread communications (#3294)
- [x] Cross-platform thread library (#3294)
- [x] cpuinfo dependency for querying cache sizes and instruction sets available (#3292)
- [x] Pluggable task executor and basic thread pool implementation for executing queues of tasks
- [x] HAL command buffer/queue integration using the task executor
- [x] Plumbing of workgroup xyz/count/etc into dispatched executables

**Comment by benvanik** [comment]
Done!
