### ISSUE TITLE
Make VMVX fast (enough).

### ISSUE THREAD

**Issue by benvanik** [google/iree#5880]
**Project tracking work items:** https://github.com/google/iree/projects/30

VMVX has landed in #5536. This initial version has zero vector intrinsics and uses the full scalar lowering path to run on the IREE VM. This is naturally _quite slow_.

There are a few major pieces of low hanging fruit, each of which can improve performance 10-100x:
* [ ] reduce loop/indexing overhead (#5544, #5547, etc)
* [ ] add vmvx instrinsics for the most critical operations (like matmul inner tiles) (#5819)
* [ ] fix work distribution to avoid teeny tiny tiles and so much overhead (#5548)

**Comment by benvanik** [comment]
Closing in favor of using issues directly given that this is on the backlog.
