### ISSUE TITLE
Enable large address space (64-bit) support end-to-end.

### ISSUE THREAD

**Issue by benvanik** [google/iree#8661]
Tracking the work to get TB-sized models running. A lot of environmental issues come up in those cases that we won't be focusing on (where is that TB of data stored, how the data is efficiently streamed into memory, or how is it divided into SPMD-style sharded programs, etc), but for reasonably sized sharded workloads we should be able to get to a good place.

Known issues by area:

Input:
* [x] MHLO is running [i64->i32 truncation](https://github.com/google/iree/blob/4a93d2569e44f53b19921e47840cf8576f87bf1d/iree/compiler/Dialect/Flow/Transforms/TypeConverter.cpp#L37) and that needs to die

Codegen:
* [ ] SPIR-V needs to emulate i64 (#8702)

Streams:
* [ ] `index` needs to be split into host/device types in the compiler (#8043)
* [x] Dispatch argument marshaling needs to handle these new types for packing
* [x] Constant/allocation packing needs to have the right resource constraints to limit allocation size

HAL:
* [x] Resource constraints here too for streaming allocations (removed attr in #9127, no longer required)
* [x] #9158

VM:
* [x] VM imports need to be able to take 64-bit values (#8051)
* [x] #9157
* [x] #9153

**Comment by benvanik** [comment]
There's some optimizations that can be done (like in #9137 and others related to constants), but this seems to work now. @powderluv offered some larger models and I'll wait to verify those before closing this out.

**Comment by powderluv** [comment]
https://storage.googleapis.com/shark-public/90B.mlir 90Billion params and 650GB file. It was generated a few weeks ago.

**Comment by stellaraccident** [comment]
That sound is Ben deleting old video games from his computer :)

**Comment by benvanik** [comment]
We'll see if I can compile that without running out of swap :P

**Comment by powderluv** [comment]
I added a 9.7T SSD as swap on my VM 😂

**Comment by powderluv** [comment]
and an 18B parameter model https://storage.googleapis.com/shark-public/18B.mlir

**Comment by benvanik** [comment]
Closing for now as this seems to work. #9275 will make the configuration easier but is going to take some time.
